# This is a basic workflow to help you get started with Actions

name: 01 - Building Blocks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo Hello, world!

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Failed step
        run: |
          echo "Hi, i will fail :("
          exit 1
      - name: Say goodbye
        run: echo "Goodbye!"
