name: 02 - Workflow events

on: 
  push:
    paths:
      - '.github/workflows/02-workflow-events.yaml'
  pull_request:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
    
jobs: 
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Show the trigger
        run: |
          echo "Event type: ${{ github.event_name }}"