name: 02 - Workflow events

on: 
  push:
    branches:
      - "[main]"
    paths:
      - '.github/workflows/02-workflow-events.yaml'
  
  pull_request:

  schedule:
    - cron: "30 9 * * *"
  
  workflow_dispatch:
    
jobs: 
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Print time
        run: echo $(date)

      - name: Show the trigger
        run: |
          echo "Event type: ${{ github.event_name }}"
