name: 02 - Workflow events

on: 
  push:
    paths:
      - '.github/workflows/02-workflow-events.yaml'

jobs: 
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Show the trigger
        run: |
          echo "Event type: ${{ github.event_name }}"